export const MATERIAL_RECEIPT_REQUEST = "MATERIAL_RECEIPT_REQUEST";
export const MATERIAL_RECEIPT_SUCCESS = "MATERIAL_RECEIPT_SUCCESS";
export const MATERIAL_RECEIPT_FAILS = "MATERIAL_RECEIPT_FAILS";

export const MATERIAL_HEADER_REGISTER_REQUEST =
  "MATERIAL_HEADER_REGISTER_REQUEST";
export const MATERIAL_HEADER_REGISTER_SUCCESS =
  "MATERIAL_HEADER_REGISTER_SUCCESS";
export const MATERIAL_HEADER_REGISTER_FAIL = "MATERIAL_HEADER_REGISTER_FAIL";
